name: Publish Docker image
on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:    
      - master   
jobs:
    push_to_registry:
        name: Push Docker image to Docker Hub
        runs-on: ubuntu-latest
        steps:
          - name: Check out the repo
            uses: actions/checkout@v2
        
          - name: Build & push Docker image to Docker Hub
            uses: docker/build-push-action@v1
            with:
              image: seendsouza/acn-bot
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}
              tags: latest
              tag_with_sha: true
